FROM php:7.4-apache

# Add better PHP extension installer
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions

# Install and enable xdebug
RUN install-php-extensions xdebug && docker-php-ext-enable xdebug

# Following packages are required for some php addons
RUN apt-get update && apt-get install -y zlib1g-dev libpng-dev libsqlite3-dev

# Install and enable extensions required by some plugins
RUN REQUIRED_EXTENSIONS="gd mysqli" && install-php-extensions $REQUIRED_EXTENSIONS && \
    docker-php-ext-enable $REQUIRED_EXTENSIONS

# Fix ownership
RUN usermod -u 1000 www-data

# Apply changes & restart apache service
RUN a2enmod rewrite && service apache2 restart
