FROM php:7.4-apache

# Install and enable xdebug
RUN pecl install xdebug && docker-php-ext-enable xdebug

# Following packages are required for some php addons
RUN apt-get update && apt-get install -y zlib1g-dev libpng-dev libsqlite3-dev

# Install and enable extensions required by some plugins
RUN docker-php-ext-install gd mysqli pdo_sqlite \
    && docker-php-ext-enable gd mysqli pdo_sqlite

# Apply changes & restart apache service
RUN a2enmod rewrite && service apache2 restart

# Fix ownership
RUN chown -R www-data:www-data /var/www/html && chmod -R 0770 /var/www/html